version: "3.3"

networks:
  host:

services:
  springboot-postgres:
    image: springboot-postgres:1.0
    container_name: backend
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    expose:
      - "8081"
    depends_on:
      - myapp-postgres
    links:
      - myapp-postgres
    networks:
      - host
    hostname: localhost
    environment:
      - WAIT_HOSTS=myapp-postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  myapp-postgres:
    image: postgres:13.3
    container_name: bd
    environment:
      - POSTGRES_DB=MyAppDb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    networks:
      - host

