version: "3.3"

networks:
  host:

services:
  springboot-postgres:
    image: springboot-postgres:1.0
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    expose:
      - "8081"
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - host
    hostname: localhost

