version: "3.3"

networks:
  host:

services:
  springboot-mysql:
    image: springboot-mysql:1.0
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    expose:
      - "8081"
    depends_on:
      - myapp-mysql
    links:
      - myapp-mysql
    networks:
      - host
    hostname: localhost
    environment:
      - WAIT_HOSTS=myapp-mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  myapp-mysql:
    image: mysql:8.0
    container_name: bd
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin -uroot -proot ping' ]
      interval: 10s
      timeout: 2s
      retries: 10
    networks:
      - host
